language: clojure
sudo: false
lein: lein2
script: xvfb-run -a -- lein2 doo slimer tests once
jdk:
  - openjdk7

before_install:
  - echo "Installing slimer..."
  - wget http://download.slimerjs.org/releases/0.9.6/slimerjs-0.9.6.zip
  - unzip slimerjs-0.9.6.zip
  - export PATH="$PWD/slimerjs-0.9.6/:$PATH"
